/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    Calendar: typeof import('primevue/calendar')['default']
    Card: typeof import('primevue/card')['default']
    ConfirmModal: typeof import('./src/components/common/ConfirmModal.vue')['default']
    DetailsHeader: typeof import('./src/components/common/DetailsHeader.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    EditableCell: typeof import('./src/components/schedule/EditableCell.vue')['default']
    GanttDiagram: typeof import('./src/components/schedule/GanttDiagram.vue')['default']
    GanttGroup: typeof import('./src/components/schedule/GanttGroup.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MemberDetails: typeof import('./src/components/common/MemberDetails.vue')['default']
    OverlayPanel: typeof import('primevue/overlaypanel')['default']
    ProjectForm: typeof import('./src/components/common/ProjectForm.vue')['default']
    ProjectPaginator: typeof import('./src/components/common/ProjectPaginator.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RowGroup: typeof import('./src/components/schedule/RowGroup.vue')['default']
    RowHeader: typeof import('./src/components/schedule/RowHeader.vue')['default']
    ScrollPanel: typeof import('primevue/scrollpanel')['default']
    Sidebar: typeof import('primevue/sidebar')['default']
    SidebarMenu: typeof import('./src/components/common/SidebarMenu.vue')['default']
    SpinnerLoader: typeof import('./src/components/common/SpinnerLoader.vue')['default']
    SplitButton: typeof import('primevue/splitbutton')['default']
    TopNavbar: typeof import('./src/components/common/TopNavbar.vue')['default']
    UserInfo: typeof import('./src/components/common/UserInfo.vue')['default']
  }
}
